name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Use your project's required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build # Replace with your project's build command

    # If your build command generates output to a folder (e.g., 'build' or 'dist'), you can use an action like "peaceiris/actions-gh-pages" to deploy that folder to gh-pages branch
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # Change to your static files directory
