name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy-jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Adjust to your Jekyll site's Ruby version

      - name: Install dependencies
        run: |
          bundle install
          npm install
          
      - name: Build Jekyll site
        run: bundle exec jekyll build
        
      - name: Run any Node.js or npm commands
        run: |
          npm run build --if-present
          # Add any other Node.js/npm commands here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Adjust based on your Jekyll site's build output directory
